### ISSUE TITLE
[Bug] layout.handlebars not picked up in production env

### ISSUE THREAD

**Issue by kapv89** [inadarei/nodebootstrap#22]
For some reason, `res.render` calls are not rendering the layout in production env. I have tried setting up the 'views' setting in runningApp to point to the top level 'views' folder, but that didn't work, So kinda stuck over there.

**Comment by inadarei** [comment]
Do you mean: it works on dev, but not in production?

**Comment by kapv89** [comment]
Yes, specifically, when I start the server using `./bin/dev_start.sh` , handlebars layout is rendered. But when I start the server using `./bin/start.sh`, layout is completely ignored.

**Comment by inadarei** [comment]
Thanks, Kapil. That is super helpful. Let me investigate and get back to you.

**Comment by inadarei** [comment]
Update: still working on this one… So far what I can say: hbs does some really weird stuff :) It is the module for handlebars integration with Express tho

**Comment by inadarei** [comment]
Update: found the culprit. Fix working locally. Will be pushing a new version soon.

**Comment by inadarei** [comment]
Fix in progress: https://github.com/inadarei/nodebootstrap/pull/25

**Comment by inadarei** [comment]
Merged
