### ISSUE TITLE
Please run the shell script from project's root folder

### ISSUE THREAD

**Issue by ummmrita** [inadarei/nodebootstrap#31]
I am running the dev_start script from the project's root, still I get this message. The script does not run after this.

**Comment by inadarei** [comment]
Can you please provide some more details? Any chance you could record a screencast of what you are seeing?

**Comment by ummmrita** [comment]
I have installed this and ran ./bion/dev_start.sh
I got a message that asked me to run it from the project root. That's all.

**Comment by ummmrita** [comment]
Sorry ^ was by mistake.

**Comment by inadarei** [comment]
ok, no problem. Glad ti worked out.

**Comment by megaz** [comment]
I'm still getting this issue - running ./bin/dev_start.sh from the hello directory described in the README

**Comment by inadarei** [comment]
@megaz please provide information about:

1. version of operating system
2. version of Node
3. steps to reproduce your problem.

Thanks

**Comment by nikkwong** [comment]
This happens when ```npm install``` has not been run for whatever reason, as per: 

./bin/start.sh 

    if [ ! -d "$PWD/node_modules" ]; then
      echo "Please run the shell script from project's root folder"
      exit

**Comment by inadarei** [comment]
If you haven't run npm install, you should get error. What is the problem? The error message being ambiguous?

**Comment by nikkwong** [comment]
No problem. Just pointing it out if others can't figure out what is happening :-)

**Comment by inadarei** [comment]
awesome. Thanks!
