### ISSUE TITLE
maxBuffer Exceeded Error

### ISSUE THREAD

**Issue by KalenAnson** [inadarei/nodebootstrap#44]
Not sure if this is an error specific to node or what. Here is the error:

    /usr/local/lib/node_modules/nodebootstrap/bin/nodebootstrap:82
              if (err) { throw err; process.exit(); }
                         ^

    Error: stderr maxBuffer exceeded.
        at Socket.<anonymous> (child_process.js:258:12)
        at emitOne (events.js:77:13)
        at Socket.emit (events.js:169:7)
        at readableAddChunk (_stream_readable.js:146:16)
        at Socket.Readable.push (_stream_readable.js:110:10)
        at Pipe.onread (net.js:523:20)

Executing the command `nodebootstrap build myApp`.

Here is the point at which the build command died, from `/usr/local/lib/node_modules/nodebootstrap/bin/nodebootstrap`:

    var setupcli = cli.execFile("./setup.sh", [], {"cwd" : projectPath}, function(err, stdout, stderr) {
        if (err) { throw err; process.exit(); }

Running:
Node 4.0.0
npm 2.14.2
OS X 10.10.3

**Comment by KalenAnson** [comment]
So I ran the `setup.sh` script manually and everything installed normally.

FWIW the problem may be the fact that I have `npm` configured to operate verbosely, generating loads of debug info while installing new dependancies. Perhaps this debug output overran the `stderr` or `stdout` buffer.

**Comment by inadarei** [comment]
Yeap,

an overly verbose output would definitely be able to exceed buffer sizes and lead to the problem you are describing.
