### ISSUE TITLE
Nodejs version control for Dockerfile

### ISSUE THREAD

**Issue by jhnlsn** [inadarei/nodebootstrap#48]
Is it possible to move the setup of nodejs into the local Dockerfile?  I'm not 100% sure how all the docker image extension stuff works so not sure if this is the right way.

Would like an easier way to control which version of node is setup in the docker image and it seems like it would be done by setting this up in the local Dockerfile.

**Comment by inadarei** [comment]
Great question, John.

This should be done using environmental variables. I will add a documentation of Howto for this, shortly.

**Comment by inadarei** [comment]
Update: this should be changed by indicating proper base docker image in Dockerfile.
