### ISSUE TITLE
API mode vs. APP mode.

### ISSUE THREAD

**Issue by inadarei** [inadarei/nodebootstrap#50]
Rails 5.x has introduced an interesting concept of [API Mode](http://weblog.rubyonrails.org/2015/12/18/Rails-5-0-beta1/) allowing developers to bootstrap a project with minimal settings required for just API development (vs. the whole thing). You can do it by:

```console
> rails new backend --api
```

Based on user feedback, we need the same thing in Nodebootstrap. Except, considering the role and specificities of Node, I believe the default in this case should be "api mode" and "full mode" should be optional.

**Comment by jhnlsn** [comment]
I agree that "full" or "web stack" mode should be optional and the default should be api mode.
