### ISSUE TITLE
Run on https

### ISSUE THREAD

**Issue by nikkwong** [inadarei/nodebootstrap#52]
How can we achieve this? 

Apparently it's not as simple as: 

````
  if (is_http_thread) {
    http = https.createServer(app);
    http.listen(443);
  }
````

**Comment by inadarei** [comment]
If you don't mind me asking – is this necessary?

Having Node handle https doesn't sound like a good idea. That's what Nginx and API Gateways are for.

**Comment by nikkwong** [comment]
Ok definitely valid. Closing.
