### ISSUE TITLE
Unable to run container

### ISSUE THREAD

**Issue by megaz** [inadarei/nodebootstrap#59]
Getting the following error when trying to run a docker container using the current master branch

I have both docker-machine and docker-compose installed locally 

```
dev:~$ docker -v
Docker version 1.11.0-rc5, build 6178547

16:52 $ docker-compose -v
docker-compose version: 1.4.0
```

This is the error that i am getting
```
npm ERR! Linux 4.1.19-boot2docker
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "docker-start"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! nodebootstrap-based-app@ docker-start: `docker-compose run -d -p 3000 app node server.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nodebootstrap-based-app@ docker-start script 'docker-compose run -d -p 3000 app node server.js'.
npm ERR! This is most likely a problem with the nodebootstrap-based-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     docker-compose run -d -p 3000 app node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodebootstrap-based-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/application/npm-debug.log

> nodebootstrap-based-app@ docker-start /opt/application
> docker-compose run -d -p 3000 app node server.js

sh: docker-compose: not found
```

For building the Docker image, i'm running the following command 

`docker build -t megaz/hello .` 

Then when running the container, I am running the following command 

`docker run -ti -p 5000:3000 megaz/hello`

**Comment by inadarei** [comment]
You need to have docker compose installed. Seems like that is missing on your system.

**Comment by megaz** [comment]
I have docker-compose installed locally and I am able to get the container running without any errors using  `docker-compose run -d -p 3000:3000 app node server.js` but it fails when I try and run the container using `docker run -ti -p 5000:3000 megaz/hello`.

**Comment by inadarei** [comment]
I believe the problem is that you are trying to run docker manually, instead of using provided npm scripts and you are missing a number of environmental variables required. Take a look at: https://github.com/inadarei/nodebootstrap/blob/master/docker-compose.yml
