### ISSUE TITLE
Document Docker Dependencies?

### ISSUE THREAD

**Issue by StevenBlack** [inadarei/nodebootstrap#70]
Hi!  This is a suggestion.

I'm evaluating node bootstrapping and this repo looks awesome except the Docker piece seems overkill for our immediate needs.

If the docker dependencies were documented or commented, removing the Docker elements would be a snap.

**Comment by inadarei** [comment]
@StevenBlack Docker support is completely optional. You don't have to use it or even support it.

**Comment by StevenBlack** [comment]
Thanks @inadarei I took it in a different direction.
