### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by ktyacke** [inadarei/nodebootstrap#92]
Receiving the below error when creating a new webapp. If I try to run the app using start.sh everything executes; however, the page (localhost:3000) returns raw JSON. Any pointers?

`bootstrap#3.0.3 public/bower_components/bootstrap
└── jquery#2.0.3
added 327 packages in 12.432s
fs.js:1053
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink './setup.sh'
    at Object.fs.unlinkSync (fs.js:1053:18)
    at /usr/local/lib/node_modules/nodebootstrap/nodebootstrap:252:18
    at ChildProcess.exithandler (child_process.js:244:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12)`

Thanks!

**Comment by inadarei** [comment]
@ktyacke just to be clear, can you please provide the full command you are using to create your project? Thank you

**Comment by Lawrence-Sproul** [comment]
i get the same error using "nodebootstrap appname -m webapp"
I have tried different appnames and different start directories.
i used "npm install nodebootstrap -g" to install nodebootstrap. this seems to install without issue.
I am on cloud9 nodejs template.

**Comment by inadarei** [comment]
Thank you for the detailed report. i was able to reproduce this problem. Working on a fix.

**Comment by inadarei** [comment]
Fixed in nodebootstrap@4.3.4

Please update with `npm install -g nodebootstrap`
